repos:
- repo: git@github.com:pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
    - id: trailing-whitespace
      exclude: .proto
      args: ['--markdown-linebreak-ext=md']
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.3
    hooks:
    -   id: seed-isort-config
        args: ['--application-directories=./src']

-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
- repo: git@github.com:humitos/mirrors-autoflake.git
  rev: v1.1
  hooks:
    - id: autoflake
      exclude: .*\/dashboards\/service\/auto\/.*py
      args: ['--in-place', '--remove-all-unused-imports']
