class Symbol:
    BTCUSD = "BTC-USD"
    ETHUSD = "ETH-USD"
    ETHBTC = "ETH-BTC"
    BTCEUR = "BTC-EUR"
    ETHEUR = "ETH-EUR"

    BCHUSD = "BCH-USD"
    BCHEUR = "BCH-EUR"
    BCHBTC = "BCH-BTC"
    BCHETH = "BCH-ETH"

    XLMUSD = "XLM-USD"
    XLMEUR = "XLM-EUR"
    XLMBTC = "XLM-BTC"
    XLMETH = "XLM-ETH"

    PAXUSD = "PAX-USD"
    PAXEUR = "PAX-EUR"
    BTCPAX = "BTC-PAX"
    ETHPAX = "ETH-PAX"
    BCHPAX = "BCH-PAX"
    XLMPAX = "XLM-PAX"

    LTCUSD = "LTC-USD"
    LTCEUR = "LTC-EUR"
    LTCPAX = "LTC-PAX"
    LTCBTC = "LTC-BTC"

    USDTUSD = "USDT-USD"
    USDTEUR = "USDT-EUR"
    BTCUSDT = "BTC-USDT"
    ETHUSDT = "ETH-USDT"
    BCHUSDT = "BCH-USDT"
    LTCUSDT = "LTC-USDT"

    ALGOUSD = "ALGO-USD"
    ALGOBTC = "ALGO-BTC"
    ALGOUSDT = "ALGO-USDT"

    DGLDUSD = "DGLD-USD"
    DGLDBTC = "DGLD-BTC"

    BTCGBP = "BTC-GBP"
    ETHGBP = "ETH-GBP"

    BTCTRY = "BTC-TRY"
    ETHTRY = "ETH-TRY"
    USDTTRY = "USDT-TRY"
    LTCTRY = "LTC-TRY"
